config/routes.rb
Rails.application.routes.draw do
  resources :points, only: [:index]
  resources :users, only: [:index]
   
  get 'user/:id/historic' , to: 'users#historic', as: 'historic'
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  delegate :name, to: :user, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
    points = Point.all
    @points = TimerDecorator.wrap(points)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:historic]

  def index
    users = User.all
    @users = TimerDecorator.wrap(users)
  end

  def historic
    points =  Point.where(user_id: params[:id])
    @points = TimerDecorator.wrap(points)
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calc_points user
    sum_points = 0
    max_points = 3126
    points = Point.where(user_id: user.id)
    points.each { |point| sum_points += point.score } 
    sum_points = max_points if sum_points > max_points
    return sum_points
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Challenge
    = csrf_meta_tags
    = csp_meta_tag
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  body
    .header.container-fluid 
      
      .title Dito ~ Challenge
    
    = yield

app/views/points/index.html.slim
.container-fluid.painel
  h1 #{t('helpers.all')} #{Point.model_name.human count: @points.count}
  hr
  table.table.datatables
    thead.thead-dark
      tr
        th scope="col"  = t('attributes.score')
        th scope="col"  = t('attributes.score_date')
        th scope="col"  = t('attributes.user')
        th scope="col"  = t('helpers.actions') 
    tbody
      - @points.each do |point|
        tr
          th = point.score
          td = point.formatted_date
          td = point.name
          td 
            = button_to t('helpers.historic') , historic_path(point.user), method: :get, class: 'btn btn-primary'

app/views/users/historic.html.slim
.container-fluid.painel
  h1 #{Point.model_name.human count: @points.count} #{t('helpers.from')} #{@user.name}
  hr
  h3 #{t('helpers.total_points')} : #{calc_points(@user)}
  hr
  table.table.datatables
    thead.thead-dark
      tr
        th scope="col"  = t('attributes.score')
        th scope="col"  = t('attributes.score_date')
        th scope="col"  = t('helpers.actions') 
    tbody
      - @points.each do |point|
        tr
          th = point.score
          td = point.formatted_date
          td = button_to t('helpers.cancel') , users_path, method: :get, class: 'btn btn-primary'

app/views/users/index.html.slim
.container-fluid.painel
  h1 = User.model_name.human count: @users.count
  hr
  = button_to t('helpers.points') , points_path, method: :get, class: 'btn btn-default'
  hr
  table.table.datatables
    thead.thead-dark
      tr
        th scope="col"  = t('attributes.code')
        th scope="col"  = t('attributes.name')
        th scope="col"  = t('attributes.score')
        th scope="col"  = t('attributes.created_at')
        th scope="col"  = t('helpers.actions') 
    tbody
      - @users.each do |user|
        tr
          th = user.code
          td = user.name
          td = calc_points(user)
          td = user.formatted_datetime
          td 
            = button_to t('helpers.historic') , historic_path(user), method: :get, class: 'btn btn-primary'